<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.github.swsk33</groupId>
	<artifactId>code-post-parent</artifactId>
	<version>2.0.0</version>
	<packaging>pom</packaging>
	<name>CodePost - Parent</name>
	<description>CodePost是一个简单的邮件验证码生成和发送框架，用于简化后端服务中生成、发送和验证邮件验证码的逻辑</description>
	<url>https://github.com/swsk33/code-post</url>

	<!-- 需要构建的子模块 -->
	<modules>
		<module>code-post-core</module>
		<module>code-post-spring-boot-starter</module>
	</modules>

	<properties>
		<java.version>1.8</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<spring.boot.starter.version>2.7.11</spring.boot.starter.version>
		<maven.test-plugin.version>3.5.5</maven.test-plugin.version>
	</properties>

	<licenses>
		<license>
			<name>Apache License Version 2.0</name>
			<url>https://www.apache.org/licenses/</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<url>https://github.com/swsk33/code-post</url>
		<connection>git@github.com:swsk33/code-post.git</connection>
		<developerConnection>git@github.com:swsk33/code-post.git</developerConnection>
	</scm>

	<developers>
		<developer>
			<name>守望时空33</name>
			<email>yanhanhui2001a@163.com</email>
			<url>https://github.com/swsk33</url>
		</developer>
	</developers>

	<!-- 公用依赖 -->
	<dependencies>
		<!-- Lombok 注解支持 -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<!-- 依赖版本管理 -->
	<dependencyManagement>
		<dependencies>
			<!-- Lombok 注解支持 -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.46</version>
			</dependency>

			<!-- Hutool 实用工具 -->
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-bom</artifactId>
				<version>5.8.44</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- JUnit 单元测试 -->
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>6.0.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- CodePost 核心 -->
			<dependency>
				<groupId>io.github.swsk33</groupId>
				<artifactId>code-post-core</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- CodePost Spring Boot Starter -->
			<dependency>
				<groupId>io.github.swsk33</groupId>
				<artifactId>code-post-spring-boot-starter</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<!-- 插件版本管理 -->
		<pluginManagement>
			<plugins>
				<!-- 测试相关插件 -->
				<plugin>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven.test-plugin.version}</version>
				</plugin>

				<plugin>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>${maven.test-plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<!-- Maven 源码编译插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>

			<!-- Sonatype 中央仓库发布插件 -->
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
				<version>0.10.0</version>
				<extensions>true</extensions>
				<configuration>
					<publishingServerId>central</publishingServerId>
				</configuration>
			</plugin>

			<!-- 源码生成插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<!-- Javadoc 文档生成插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.12.0</version>
				<configuration>
					<show>private</show>
					<nohelp>true</nohelp>
					<doclint>all,-missing</doclint>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<!-- GPG 签名插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>3.2.8</version>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>