# 服务端配置
server:
  port: 8802

# CodePost邮件配置
io:
  github:
    swsk33:
      code-post:
        core:
          # 发件邮箱的SMTP服务器
          smtp-host: "smtp.163.com"
          # 用于发件的邮箱
          email: "${EMAIL}"
          # 发件邮箱密码（或者是授权码）
          password: "${MAIL_PASSWORD}"
          # 是否启用TLS安全加密
          # 默认：true
          enable-tls: true
          # 用于存放管理验证码过期的方式
          # 可用值：
          # thread_pool - 使用本地线程池
          # redis - 使用Redis
          # 默认：thread_pool
          code-storage: "${CODE_STORAGE:thread_pool}"
          # 验证码格式
          # 可用值：
          # number - 纯数字
          # char - 纯英文字母
          # number_char - 字母数字组合
          # 默认：number
          code-format: "number"
          # 验证码长度
          # 默认：6
          code-length: 6
          # 你的网站名（会在验证码邮件标题显示）
          # 默认：网站名
          site-name: "xxx博客"
          # 是否使用HTML网页邮件
          # 默认：false
          enable-html: true
          # 模板文件所在目录，需要以file:或者classpath:开头，分别代表文件系统路径或者类路径
          template-path: "classpath:templates"
          # 用于邮件验证码内容的模板文件名（该项只填写文件名！该配置项会和templatePath配置值拼接得到完整文件路径）
          # 若不配置template-path和code-template-name或者配置模板路径不存在，则发送验证码邮件时会使用内置默认模板
          code-template-name: "test-template.ftlh"

# Spring Data Redis配置
spring:
  redis:
    # 单机
    host: "${REDIS_HOST}"
    port: ${REDIS_PORT}
    password: "${REDIS_PASSWORD}"
    # 哨兵
    #    sentinel:
    #      master: "my-master"
    #      nodes: "202.114.148.161:7003,202.114.148.161:7004,202.114.148.161:7005"
    # Cluster分片
    cluster:
      nodes: "202.114.148.161:8001,202.114.148.161:8002,202.114.148.161:8003,202.114.148.161:8004,202.114.148.161:8005,202.114.148.161:8006"